// <auto-generated />
namespace komyuter.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addcenterlatlonroute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcenterlatlonroute));
        
        string IMigrationMetadata.Id
        {
            get { return "202003062244275_add-center-latlon-route"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
