// <auto-generated />
namespace komyuter.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class rtservicealerts2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rtservicealerts2));
        
        string IMigrationMetadata.Id
        {
            get { return "202003290915100_rt-service-alerts2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
