// <auto-generated />
namespace komyuter.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class rtservicealerts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rtservicealerts));
        
        string IMigrationMetadata.Id
        {
            get { return "202003290913323_rt-service-alerts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
