// <auto-generated />
namespace komyuter.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class longitudeupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(longitudeupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202004061157032_longitude-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
