// <auto-generated />
namespace komyuter.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class navirtservicealertsrtid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(navirtservicealertsrtid));
        
        string IMigrationMetadata.Id
        {
            get { return "202003310924466_navi-rt-service-alerts-rt-id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
