// <auto-generated />
namespace komyuter.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class stoptimeremovesecondsfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stoptimeremovesecondsfield));
        
        string IMigrationMetadata.Id
        {
            get { return "202002261307225_stop-time-remove-seconds-field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
