// <auto-generated />
namespace komyuter.web_agency.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class newdbnavi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newdbnavi));
        
        string IMigrationMetadata.Id
        {
            get { return "202003301105554_new-db-navi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
